.TH "easytag" "1" "0.15" "Baruch Even" "System General Commands Manual"
.SH "NAME"
.LP 
easytag \- Edit and View ID3 tags on MP3 files
.SH "SYNTAX"
.LP 
easytag

.SH "DESCRIPTION"
.LP 
EasyTAG is an utility for viewing, editing and writing the ID3 tags of MP3 files, using a GTK+ interface.

.LP
EasyTAG is controlled only from a GUI and thus has no command line options.

.LP 
Currently EasyTAG supports the following features:

.IP * 2
Viewing, editing, writing ID3 TAGs of MP3 files,

.IP * 2 
Process all MP3 files of the selected directory,
.IP * 2 
Ability to browse subdirectories,
.IP * 2 
Recursion for tagging, removing, renaming, saving...,
.IP * 2 
Easy directory selection with a tree browser,
.IP * 2 
Supports ID3v1, ID3v1.1 tags,
.IP * 2 
Scan file for automatic tagging (using masks),
.IP * 2 
Scan tag for automatic renaming file (using masks),
.IP * 2 
Rename mp3 file,
.IP * 2 
Can apply a field (artist, title,...) to all other files,
.IP * 2 
Display MP3 header informations,
.IP * 2 
Can load a character translation file.
.SH "AUTHORS"
.LP 
Baruch Even <baruch@debian.org> wrote this manpage for Debian, it may be used freely with no limitation in any other packaging or otherwise.

.LP 
Jerome Couderc <easytag@gmail.com> is the author of easytag.
